const DAY=864e5,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state={user:null,cities:[],people:[],events:[],schedules:[],dismissedSchedules:[],users:[]},currentCity="",pendingEvent={title:"Коллективная медитация",eventDate:new Date().toISOString()},attendanceSelected=new Set(),attendanceExisting=new Set(),addingFromAttendance=false,editingPersonId=null,period=30;
const practiceLabels={unknown:"Пока неизвестно",none:"Не практикует",sometimes:"Практикует иногда",sessions_only:"Практикует иногда",daily:"Практикует каждый день",home_regular:"Практикует каждый день",twice_daily:"Практикует каждый день дважды",twice_daily_initiation:"Каждый день дважды, хочет инициацию"},sourceLabels={unknown:"Не указано",meditation_lessons:"Проект «Уроки медитации»",vk:"Группа ВКонтакте",avito:"Авито",marg:"Порекомендовал Марг",subscriber:"Порекомендовал подписчик",other:"Другое"},contactLabels={message:"Написали",call:"Позвонили",meeting:"Личная встреча",material:"Отправили материал"},weekdays=[["Пн",1],["Вт",2],["Ср",3],["Чт",4],["Пт",5],["Сб",6],["Вс",0]];
const journeyStages=[
 {id:"chat",title:"Приглашение в чат",wait:"Доступно после второго визита",steps:[{key:"chat_invited",label:"Пригласили",next:"пригласить в чат"},{key:"chat_joined",label:"Добавлен",next:"добавить в чат"}]},
 {id:"book",title:"Книга",steps:[{key:"book_acquired",label:"Приобрёл книгу",next:"предложить книгу"}]},
 {id:"basic",title:"Базовый курс",steps:[{key:"basic_started",label:"Начал",next:"предложить базовый курс"},{key:"basic_completed",label:"Завершил",next:"помочь завершить базовый курс"}]},
 {id:"kdi",title:"К-Д-И",steps:[{key:"kdi_started",label:"Начал",next:"предложить К-Д-И"},{key:"kdi_completed",label:"Завершил",next:"помочь завершить К-Д-И"}]},
 {id:"practice",title:"Регулярная практика",steps:[{key:"twice_daily",label:"Медитирует дважды в день",auto:true}]},
 {id:"curator",title:"Куратор",steps:[{key:"curator_offered",label:"Предложили",next:"предложить куратора"},{key:"curator_assigned",label:"Назначен",next:"назначить куратора"}]},
 {id:"acharya",title:"Знакомство с ачарьей",steps:[{key:"acharya_offered",label:"Предложили",next:"предложить знакомство с ачарьей"},{key:"acharya_met",label:"Познакомился",next:"организовать знакомство с ачарьей"}]},
 {id:"retreat",title:"Ретрит",steps:[{key:"retreat_invited",label:"Пригласили",next:"пригласить на ретрит"},{key:"retreat_attended",label:"Был на ретрите",next:"поддержать участие в ретрите"}]},
 {id:"mantra",title:"Получил мантру",steps:[{key:"mantra_received",label:"Получил",next:"обсудить получение мантры"}]},
 {id:"initiation",title:"Получил инициацию",important:true,steps:[{key:"initiation_received",label:"Получил",next:"поддержать путь к инициации"}]}
];
const journeyTotal=journeyStages.reduce((sum,stage)=>sum+stage.steps.length,0);
const achievementDone=(p,key)=>Boolean(p.achievements?.[key]);
function journeyProgress(p){return journeyStages.reduce((sum,stage)=>sum+stage.steps.filter(step=>achievementDone(p,step.key)).length,0)}
function journeyNext(p){for(const stage of journeyStages){if(stage.id==="chat"&&Number(p.visits)<2&&!stage.steps.every(step=>achievementDone(p,step.key)))return"После второго визита — пригласить в чат";for(const step of stage.steps)if(!step.auto&&!achievementDone(p,step.key))return step.next}return"Основные этапы пройдены"}
function journeyHint(p){return`Этапы ${journeyProgress(p)}/${journeyTotal} · Далее: ${journeyNext(p)}`}
function journeyDate(value){return value?new Date(value).toLocaleDateString("ru-RU",{day:"2-digit",month:"2-digit",year:"2-digit"}):""}
function renderJourney(p){const progress=journeyProgress(p),next=journeyNext(p);return`<details class="journey"><summary><div><b>Этапы пути</b><small>${h(next)}</small></div><span>${progress}/${journeyTotal}</span></summary><div class="journey-list">${journeyStages.map(stage=>{const ready=stage.id!=="chat"||Number(p.visits)>=2||stage.steps.some(step=>achievementDone(p,step.key));return`<div class="journey-row ${stage.important?"important":""} ${stage.steps.every(step=>achievementDone(p,step.key))?"done":""}"><div class="journey-label"><b>${stage.title}</b>${!ready&&stage.wait?`<small>${stage.wait}</small>`:""}</div><div class="journey-steps">${stage.steps.map(step=>{const done=achievementDone(p,step.key),disabled=step.auto||!ready,title=done?`Отмечено ${journeyDate(p.achievements[step.key])}`:step.auto?"Отмечается автоматически":"";return`<button type="button" class="journey-step ${done?"checked":""}" title="${h(title)}" ${disabled?"disabled":""} onclick="toggleAchievement(event,${p.id},'${step.key}')"><span>${done?"✓":""}</span>${step.label}</button>`}).join("")}</div></div>`}).join("")}</div></details>`}
async function toggleAchievement(event,id,key){event.stopPropagation();const p=state.people.find(x=>Number(x.id)===Number(id));if(!p)return;const completed=!achievementDone(p,key),button=event.currentTarget,keepOpen=$("#profile .journey")?.open??false;button.disabled=true;try{await request(`/api/people/${id}/achievement`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key,completed})});p.achievements=p.achievements||{};if(completed)p.achievements[key]=new Date().toISOString();else delete p.achievements[key];renderPeople();await showProfile(id);const journey=$("#profile .journey");if(journey)journey.open=keepOpen;toast(completed?"Этап отмечен":"Отметка снята")}catch(error){button.disabled=false;toast(friendlyError(error))}}

const days=t=>Math.max(0,Math.floor((Date.now()-new Date(t).getTime())/DAY)),initials=p=>(p.first[0]+(p.last?.[0]||"")).toUpperCase(),av=id=>id%3===0?"b":id%2===0?"w":"";
function attendanceStatus(p){const visits=Number(p.visits),recent=Number(p.recentVisits);if(visits===0)return{key:"learned",text:"Узнал о практике",cls:"cold"};if(recent>=3)return{key:"regular",text:"Приходит регулярно",cls:"regular"};if(visits>3&&recent>=1)return{key:"sometimes",text:"Иногда приходит",cls:""};if(visits===1)return{key:"first",text:"Был один раз",cls:""};return{key:"repeat",text:"Приходил повторно",cls:""}}
async function request(path,options={}){return window.apiRequest(path,options)}
const cityName=id=>state.cities.find(c=>Number(c.id)===Number(id))?.name||"Город";
const h=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
function friendlyError(error){const raw=String(error?.message||error||"");if(/failed to fetch|network|load failed/i.test(raw))return"Нет соединения с интернетом. Проверьте сеть и повторите.";if(/invalid login|неверная почта/i.test(raw))return"Неверная почта или пароль.";if(/email not confirmed/i.test(raw))return"Подтвердите почту или обратитесь к администратору.";if(/email address not authorized/i.test(raw))return"Не удалось отправить письмо на эту почту. Сообщите администратору.";if(/row-level security|permission denied|not allowed/i.test(raw))return"Для этого действия нет доступа. Проверьте выбранный город.";if(/duplicate|already registered|already exists/i.test(raw))return"Такая запись уже существует.";return"Не удалось выполнить действие. Попробуйте ещё раз."}
const contactMark=p=>!Number(p.contactCount)?{cls:"none",text:"Ещё не писали"}:Number(p.contactCount)===1?{cls:"done",text:"✓ Написали первый раз"}:{cls:"done",text:`✓ Связывались: ${p.contactCount}`};
function toast(text){let t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2400)}
function renderLogin(mode="login"){
 const register=mode==="register",reset=mode==="reset",title=register?"Создать учётную запись":reset?"Восстановить пароль":"Войти в приложение",lead=register?"Укажите любую электронную почту и дважды введите пароль.":reset?"Мы отправим ссылку для создания нового пароля.":"Используйте почту и пароль, с которыми регистрировались.";
 const passwordFields=reset?"":`<label>Пароль<div class="password-field"><input id="authPassword" type="password" autocomplete="${register?"new-password":"current-password"}" minlength="8" required><button type="button" data-password-toggle="authPassword" aria-pressed="false">Показать</button></div></label>${register?'<label>Повторите пароль<div class="password-field"><input id="authPasswordConfirm" type="password" autocomplete="new-password" minlength="8" required><button type="button" data-password-toggle="authPasswordConfirm" aria-pressed="false">Показать</button></div></label>':""}`;
 document.body.innerHTML=`<main class="login"><div class="brand"><span class="brand-mark">AP</span><b>Ananda Prachar</b></div><h1>${title}</h1><p class="lead" id="authLead">${lead}</p><form id="authForm" class="auth-form">${register?'<label>Ваше имя<input id="authName" autocomplete="name" maxlength="120" required></label>':""}<label>Электронная почта<input id="authEmail" type="email" autocomplete="email" required></label>${passwordFields}<p id="authError" class="auth-error" hidden></p><button class="primary" type="submit">${register?"Зарегистрироваться":reset?"Отправить ссылку":"Войти"}</button></form>${reset?'<button class="auth-switch" id="authSwitch">Вернуться ко входу</button>':`<button class="auth-switch" id="authSwitch">${register?"Уже есть учётная запись? Войти":"Нет учётной записи? Зарегистрироваться"}</button>${register?"":'<button type="button" class="auth-forgot" id="authForgot">↺ Забыли пароль?</button>'}`}</main>`;
 $("#authSwitch").onclick=()=>renderLogin(reset?"login":register?"login":"register");
 if($("#authForgot"))$("#authForgot").onclick=()=>renderLogin("reset");
 $$("[data-password-toggle]").forEach(button=>button.onclick=()=>{const input=document.getElementById(button.dataset.passwordToggle),show=input.type==="password";input.type=show?"text":"password";button.textContent=show?"Скрыть":"Показать";button.setAttribute("aria-pressed",String(show))});
 $("#authForm").onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$("#authError").hidden=true;if(register&&$("#authPassword").value!==$("#authPasswordConfirm").value){$("#authError").textContent="Пароли не совпадают. Введите одинаковый пароль в обоих полях.";$("#authError").hidden=false;button.disabled=false;$("#authPasswordConfirm").focus();return}try{if(reset){await request("/api/auth/reset",{method:"POST",body:JSON.stringify({email:$("#authEmail").value.trim()})});$("#authForm").hidden=true;$("#authLead").textContent="Если адрес зарегистрирован, ссылка для восстановления отправлена. Проверьте почту.";return}await request(`/api/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify({name:register?$("#authName").value.trim():"",email:$("#authEmail").value.trim(),password:$("#authPassword").value})});location.reload()}catch(error){$("#authError").textContent=friendlyError(error);$("#authError").hidden=false}finally{button.disabled=false}}
}
async function load(cityId=currentCity){try{const data=await request("/api/bootstrap"+(cityId?`?cityId=${encodeURIComponent(cityId)}`:""));state=data;if(!currentCity)currentCity=String(data.user.preferredCityId||data.user.cityId||"");setupCityPicker();render();if(!currentCity)showCityOnboarding()}catch(error){if(error.status===401){renderLogin();return}const detail=h(error?.message||"unknown");document.body.innerHTML=`<main class="login"><h1>Не удалось загрузить данные</h1><p class="lead">${friendlyError(error)}</p><button class="primary" onclick="location.reload()">Попробовать снова</button><details class="error-details"><summary>Технические подробности</summary><code>${detail}</code></details></main>`}}
function setupCityPicker(){const s=$("#city");s.innerHTML='<option value="">Все города</option>'+state.cities.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");s.value=currentCity;s.disabled=false}
function showCityOnboarding(){const dialog=$("#cityOnboardingDialog"),select=$("#initialCity");if(!dialog||dialog.open)return;select.innerHTML='<option value="">Выберите город</option>'+state.cities.map(c=>`<option value="${c.id}">${h(c.name)}</option>`).join("");dialog.showModal();setTimeout(()=>select.focus(),0)}
async function saveInitialCity(){const cityId=Number($("#initialCity").value);if(!cityId){toast("Выберите город");return}const button=$("#saveInitialCity");button.disabled=true;try{await request("/api/me/preferences",{method:"PATCH",body:JSON.stringify({cityId})});currentCity=String(cityId);$("#cityOnboardingDialog").close();await load(currentCity)}catch(error){toast(friendlyError(error))}finally{button.disabled=false}}
function carePriority(p){const ranks={regular:5,sometimes:4,repeat:3,first:2,learned:1},attendance=ranks[attendanceStatus(p).key]||0,absence=Math.min(days(p.lastVisit),365),contactGap=p.lastContact?Math.min(days(p.lastContact),365):400;return attendance*100000+contactGap*100+absence}
function renderCare(){const list=[...state.people].filter(p=>Number(p.visits)>0&&days(p.lastVisit)>=7).sort((a,b)=>carePriority(b)-carePriority(a)||new Date(a.lastVisit)-new Date(b.lastVisit));$("#careCount").textContent=list.length;$("#careList").innerHTML=list.map(p=>{const mark=contactMark(p),last=p.lastContact?` · ${days(p.lastContact)} дн. назад`:"";return`<div class="care-row" data-person="${p.id}"><div class="avatar-wrap">${p.photoUrl?`<img src="${h(p.photoUrl)}" alt="">`:`<div class="av ${av(p.id)}">${initials(p)}</div>`}<span class="timer">${days(p.lastVisit)} дн.</span></div><div class="pname"><b>${h(p.first)} ${h(p.last||"")}</b><small>${attendanceStatus(p).text} · ${practiceLabels[p.practiceStatus]||practiceLabels.unknown}</small><small class="contact-mark ${mark.cls}">${mark.text}${last}</small></div><div class="care-actions"><button class="icon" title="Скопировать сообщение" onclick="event.stopPropagation();message(${p.id})">⧉</button><button class="icon" title="Зафиксировать контакт" onclick="event.stopPropagation();openContact(${p.id})">✓</button></div></div>`}).join("")||'<div class="empty-light">Сегодня нет людей с просроченным вниманием</div>'}
function renderPeople(){const q=$("#search").value.toLowerCase(),f=$("#filter").value,list=state.people.filter(p=>`${p.first} ${p.last||""} ${p.contact||""}`.toLowerCase().includes(q)).filter(p=>f==="all"||attendanceStatus(p).key===f);$("#filter").innerHTML='<option value="all">Все статусы</option><option value="learned">Только узнал</option><option value="first">Был один раз</option><option value="repeat">Пришёл повторно</option><option value="sometimes">Иногда приходит</option><option value="regular">Регулярно</option>';$("#filter").value=f;$("#peopleList").innerHTML=list.map(p=>{const s=attendanceStatus(p),timer=Number(p.visits)>0?`<small class="absence">${days(p.lastVisit)} дн. без занятия</small>`:"";return`<article class="person" data-person="${p.id}">${p.photoUrl?`<img class="person-photo" src="${h(p.photoUrl)}" alt="">`:`<div class="av ${av(p.id)}">${initials(p)}</div>`}<div class="person-main"><h3>${h(p.first)} ${h(p.last||"")}</h3><p>${practiceLabels[p.practiceStatus]||practiceLabels.unknown} · ${h(cityName(p.cityId))}</p><small class="journey-mini">${h(journeyHint(p))}</small></div><div class="meta"><span class="status ${s.cls}">${s.text}</span>${timer}</div><div class="person-actions"><button class="person-more" aria-label="Настройки человека" onclick="togglePersonMenu(event,${p.id})">•••</button><div class="person-menu" id="person-menu-${p.id}" hidden><button onclick="editPerson(event,${p.id})">Редактировать</button><button class="danger" onclick="deletePerson(event,${p.id})">Удалить</button></div></div></article>`}).join("")||'<article class="card empty">Ничего не найдено</article>'}
function datesAroundToday(weekday){const today=new Date();today.setHours(0,0,0,0);const start=new Date(today);start.setDate(start.getDate()-7);const end=new Date(today);end.setDate(end.getDate()+7);const dates=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))if(d.getDay()===weekday){const occurrence=new Date(d);occurrence.setHours(18,0,0,0);dates.push(occurrence)}return dates}
const dateKey=value=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
function renderUpcoming(){const own=state.schedules.filter(s=>!currentCity||Number(s.cityId)===Number(currentCity)),dismissed=state.dismissedSchedules||[],now=new Date(),items=own.flatMap(s=>datesAroundToday(Number(s.weekday)).map(date=>({...s,date}))).filter(x=>!state.events.some(e=>Number(e.cityId)===Number(x.cityId)&&e.title===x.eventType&&dateKey(e.date)===dateKey(x.date))).filter(x=>!dismissed.some(d=>Number(d.cityId)===Number(x.cityId)&&d.eventType===x.eventType&&dateKey(d.date)===dateKey(x.date))).sort((a,b)=>a.date-b.date);$("#upcomingPractices").innerHTML=items.map(x=>{const past=x.date<now,title=encodeURIComponent(x.eventType),date=x.date.toISOString();return`<article class="practice-card ${past?"overdue":""}"><div><small>${past?"Нужно заполнить · ":""}${x.date.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}</small><h3>${h(x.eventType)}</h3></div><div class="practice-actions"><button class="practice-dismiss" aria-label="Встреча не состоялась" title="Встреча не состоялась" onclick="dismissScheduled(event,'${title}','${date}',${x.cityId})">×</button><button class="practice-add" aria-label="Отметить участников" onclick="openAttendance(decodeURIComponent('${title}'),'${date}',${x.cityId})">＋</button></div></article>`}).join("")||'<article class="practice-empty"><b>Все встречи заполнены</b><span>Новые появятся по расписанию.</span></article>'}
async function dismissScheduled(event,encodedTitle,date,cityId){event.stopPropagation();const title=decodeURIComponent(encodedTitle),label=new Date(date).toLocaleDateString("ru-RU",{day:"numeric",month:"long"});if(!confirm(`Отметить, что встреча «${title}» ${label} не состоялась?`))return;event.currentTarget.disabled=true;try{await request("/api/schedules/dismiss",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cityId,title,date})});state.dismissedSchedules=state.dismissedSchedules||[];state.dismissedSchedules.push({cityId:Number(cityId),eventType:title,date});renderUpcoming();toast("Встреча убрана с главного экрана")}catch(error){event.currentTarget.disabled=false;toast(friendlyError(error))}}
window.dismissScheduled=dismissScheduled;
function renderEvents(){$("#eventsList").innerHTML=state.events.map(e=>`<article class="event card"><header><div class="event-meta"><span class="status">${new Date(e.date).toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}</span><span>${cityName(e.cityId)}</span></div><div class="event-actions"><button class="event-more" aria-label="Действия со встречей" aria-expanded="false" onclick="toggleEventMenu(event,${e.id})">•••</button><div class="event-menu" id="event-menu-${e.id}" hidden><button onclick="editEvent(${e.id})">Редактировать</button><button class="danger" onclick="deleteEvent(${e.id})">Удалить встречу</button></div></div></header><h3>${h(e.title)}</h3>${e.note?`<p class="event-note">${h(e.note)}</p>`:""}<div class="stats"><button onclick="showEventAttendees(event,${e.id},'all')"><b>${e.total||0}</b><span>всего</span></button><button onclick="showEventAttendees(event,${e.id},'new')"><b>${e.newcomers||0}</b><span>новых</span></button><button onclick="showEventAttendees(event,${e.id},'repeat')"><b>${Math.max(0,(e.total||0)-(e.newcomers||0))}</b><span>повторно</span></button></div></article>`).join("")||'<article class="card empty">Встреч пока нет</article>'}
function renderChecks(){const q=($("#attendanceSearch")?.value||"").trim().toLowerCase(),list=[...state.people].filter(p=>Number(p.cityId)===Number(pendingEvent.cityId)).filter(p=>`${p.first} ${p.last||""}`.toLowerCase().includes(q)).sort((a,b)=>Number(b.recentVisits)-Number(a.recentVisits)||Number(b.visits)-Number(a.visits)||a.first.localeCompare(b.first,"ru"));$("#checks").innerHTML=list.map(p=>{const id=Number(p.id),existing=attendanceExisting.has(id);return`<label class="check ${existing?"already":""}"><input type="checkbox" value="${id}" ${attendanceSelected.has(id)?"checked":""}><div class="av ${av(id)}">${initials(p)}</div><span><b>${h(p.first)} ${h(p.last||"")}</b><small>${existing?"Уже отмечен":attendanceStatus(p).text}</small><small class="journey-check">Далее: ${h(journeyNext(p))}</small></span></label>`}).join("")||'<div class="empty">Участники не найдены</div>';$$('#checks input').forEach(x=>x.onchange=()=>x.checked?attendanceSelected.add(Number(x.value)):attendanceSelected.delete(Number(x.value)))}
function renderSchedule(){const box=$("#scheduleSettings");if(!box)return;const can=state.user.role==="national_admin"||state.user.role==="city_admin",cityId=Number(currentCity||state.user.cityId);if(!can||!cityId){box.innerHTML='<p class="muted">Выберите город. Расписание меняет руководитель города или администратор.</p>';return}box.innerHTML=`<div class="weekday-grid">${weekdays.map(([label,day])=>{const on=state.schedules.some(s=>Number(s.cityId)===cityId&&Number(s.weekday)===day&&s.eventType==="Коллективная медитация");return`<label class="${on?"on":""}"><input type="checkbox" data-weekday="${day}" ${on?"checked":""}><span>${label}</span></label>`}).join("")}</div>`;$$("[data-weekday]").forEach(x=>x.onchange=()=>toggleSchedule(cityId,Number(x.dataset.weekday),x.checked))}
function renderTeam(){const box=$("#teamList"),isAdmin=state.user.role==="national_admin",mine=$("#myRole");if(isAdmin){mine.innerHTML='<option value="national_admin">Секретарь бхукти по прачару</option>';mine.disabled=true}else{mine.disabled=false;mine.value=state.user.role}$("#teamAddCity").hidden=false;if(!isAdmin){box.innerHTML="";return}box.innerHTML=state.users.map(u=>`<article class="person"><div class="av">${(u.name||u.email||"?")[0].toUpperCase()}</div><div><h3>${u.name||u.email}</h3><p>${u.email}</p></div><div class="team-controls"><select data-user-role="${u.id}"><option value="city_member">Прачарщик</option><option value="city_admin">Секретарь по прачару</option><option value="national_admin">Секретарь бхукти по прачару</option></select><select data-user-city="${u.id}"><option value="">Без города</option>${state.cities.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select></div></article>`).join("");state.users.forEach(u=>{const r=document.querySelector(`[data-user-role="${CSS.escape(u.id)}"]`),c=document.querySelector(`[data-user-city="${CSS.escape(u.id)}"]`);r.value=u.role;c.value=u.cityId||"";r.onchange=c.onchange=()=>updateUser(u.id,r.value,c.value)})}
function renderAnalytics(){const events=state.events.filter(e=>days(e.date)<period),total=events.reduce((n,e)=>n+Number(e.total||0),0),newcomerIds=new Set(events.flatMap(e=>e.newPersonIds||[])),returnedIds=new Set(events.flatMap(e=>e.repeatPersonIds||[])),regular=state.people.filter(p=>Number(p.recentVisits)>=3).length,avg=events.length?Math.round(total/events.length*10)/10:0;$("#funnel").innerHTML=[["Встреч",events.length,100],["Посещений",total,Math.min(100,total*3)],["Среднее",avg,Math.min(100,avg*5)],["Новеньких",newcomerIds.size,Math.min(100,newcomerIds.size*8)],["Вернулись повторно",returnedIds.size,Math.min(100,returnedIds.size*8)],["Регулярных сейчас",regular,Math.min(100,regular*8)]].map(x=>`<div class="frow"><span>${x[0]}</span><div class="bar"><i style="width:${x[2]}%"></i></div><b>${x[1]}</b></div>`).join("");$("#analyticsRegular").textContent=`${regular} ${regular===1?"регулярный участник":"регулярных участников"}`}
function render(){renderCare();renderPeople();renderEvents();renderChecks();renderUpcoming();renderSchedule();renderTeam();renderAnalytics();$("#monthCount").textContent=state.people.filter(p=>Number(p.visits)>0&&days(p.lastVisit)<31).length;$("#regularCount").textContent=state.people.filter(p=>Number(p.recentVisits)>=3).length}
function go(id){location.hash=id==="home"?"":id;$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===id));scrollTo({top:0,behavior:"smooth"})}window.go=go;
async function showProfile(id){const p=state.people.find(x=>Number(x.id)===Number(id));if(!p)return;const status=attendanceStatus(p),mark=contactMark(p),lastContact=p.lastContact?`Последний контакт: ${new Date(p.lastContact).toLocaleDateString("ru-RU")}`:"Контакт ещё не зафиксирован";$("#profile").innerHTML=`<button class="x" onclick="profileDialog.close()">×</button><div class="profile-title">${p.photoUrl?`<img class="profile-photo" src="${h(p.photoUrl)}" alt="">`:`<div class="av big ${av(p.id)}">${initials(p)}</div>`}<div><h2>${h(p.first)} ${h(p.last||"")}</h2><p>${h(cityName(p.cityId))} · ${h(p.contact||"Контакт не указан")}</p></div></div><div class="status-pair"><span class="status ${status.cls}">${status.text}</span><span class="status practice">${practiceLabels[p.practiceStatus]||practiceLabels.unknown}</span></div>${Number(p.visits)>0?`<div class="absence-card"><b>${days(p.lastVisit)} дней</b><span>с последнего занятия</span></div>`:""}<div class="profile-stat-grid"><div><strong>${Number(p.visits)||0}</strong><span>всего посещений</span></div><div><strong>${Number(p.recentVisits)||0}</strong><span>за последние 30 дней</span></div><div><strong>${Number(p.contactCount)||0}</strong><span>зафиксировано контактов</span></div></div>${renderJourney(p)}<section class="profile-section"><h3>О человеке</h3><div class="profile-facts"><div><span>Откуда узнал</span><b>${sourceLabels[p.source]||sourceLabels.unknown}</b></div><div><span>Познакомились</span><b>${new Date(p.acquaintanceDate||p.created).toLocaleDateString("ru-RU")}</b></div></div><div class="profile-note"><span>Комментарий</span><p>${h(p.note||"Комментариев пока нет")}</p></div></section><section class="profile-section profile-history-card"><h3>История посещений и общения</h3><div id="personHistory" class="history"><span>Загружаем…</span></div></section><div class="contact-summary ${mark.cls}"><b>${mark.text}</b><span>${lastContact}</span></div><footer class="profile-actions"><button onclick="message(${p.id})">Скопировать сообщение</button>${p.contact?`<button onclick="openContactLink(${p.id})">Открыть контакт</button>`:""}<button class="primary" onclick="openContact(${p.id})">Зафиксировать контакт</button></footer>`;if(!$("#profileDialog").open)$("#profileDialog").showModal();try{const history=await request(`/api/people/${id}/history`),all=[...history.visits.map(v=>({date:v.date,title:v.title,kind:"visit"})),...history.contacts.map(c=>({date:c.date,title:(contactLabels[c.type]||"Контакт")+(c.note?`: ${c.note}`:""),kind:"contact"}))].sort((a,b)=>new Date(b.date)-new Date(a.date));$("#personHistory").innerHTML=all.map(x=>`<div class="history-item ${x.kind}"><time>${new Date(x.date).toLocaleDateString("ru-RU",{day:"numeric",month:"short",year:"numeric"})}</time><b>${h(x.title)}</b></div>`).join("")||"<span>История пока пустая</span>"}catch{$("#personHistory").textContent="Не удалось загрузить историю"}}
async function message(id){const p=state.people.find(x=>Number(x.id)===Number(id));if(!p)return;const text=`${p.first}, здравствуйте! Как вы? Давно не виделись на практике. Хотелось узнать, всё ли хорошо и можем ли мы чем-то помочь?`;try{await navigator.clipboard.writeText(text);toast("Заботливое сообщение скопировано")}catch{const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();toast("Заботливое сообщение скопировано")}}window.message=message;
function openContact(id){const p=state.people.find(x=>Number(x.id)===Number(id));$("#contactPersonId").value=id;$("#contactPerson").textContent=`${p.first} ${p.last||""}`;$("#contactNote").value="";$("#profileDialog").close();$("#contactDialog").showModal()}window.openContact=openContact;
function openContactLink(id){const p=state.people.find(x=>Number(x.id)===Number(id)),raw=String(p?.contact||"").trim();if(!raw){toast("Контакт не указан");return}let url="";if(/^https?:\/\//i.test(raw))url=raw;else if(/^@[a-z0-9_]{3,}$/i.test(raw))url="https://t.me/"+raw.slice(1);else if(/^\+?[\d\s()\-]{7,}$/.test(raw))url="tel:"+raw.replace(/[^+\d]/g,"");if(url){window.open(url,"_blank","noopener")}else{navigator.clipboard?.writeText(raw);toast("Контакт скопирован")}}window.openContactLink=openContactLink;
async function visited(id){await request(`/api/people/${id}/visit`,{method:"POST",body:"{}"});$("#profileDialog").close();toast("Посещение отмечено");await load()}window.visited=visited;
function setVisitDate(date){const value=new Date(date);$("#visitDateInput").value=[value.getFullYear(),String(value.getMonth()+1).padStart(2,"0"),String(value.getDate()).padStart(2,"0")].join("-");$("#visitDate").textContent=value.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}

const meetingTypes=["Коллективная медитация","Карма-йога","Лекция","Дхармадеха"];
function setVisitType(title){const select=$("#visitType"),custom=$("#visitCustomType"),known=meetingTypes.includes(title);select.value=known?title:"Другое";custom.hidden=known;custom.value=known?"":title==="Другое"?"":title;pendingEvent.title=title}
function syncVisitType(){const custom=$("#visitCustomType").value.trim(),type=$("#visitType").value;pendingEvent.title=type==="Другое"?(custom||"Другое"):type;return pendingEvent.title}
function openAttendance(title="Коллективная медитация",date=new Date().toISOString(),cityId=currentCity||state.user.cityId){if(!cityId){toast("Сначала выберите город");$("#city").focus();return}pendingEvent={title,eventDate:date,cityId:Number(cityId),note:""};attendanceSelected=new Set();attendanceExisting=new Set();$("#attendanceSearch").value="";$("#visitNote").value="";$("#visitDateInput").disabled=false;$("#visitType").disabled=false;$("#visitCustomType").disabled=false;setVisitType(title);$("#visitTitle").textContent="Новая встреча";setVisitDate(date);renderChecks();$("#visitDialog").showModal()}window.openAttendance=openAttendance;
function toggleEventMenu(e,id){e.stopPropagation();const menu=$("#event-menu-"+id),opening=menu.hidden;$$(".event-menu").forEach(x=>x.hidden=true);$$(".event-more").forEach(x=>x.setAttribute("aria-expanded","false"));menu.hidden=!opening;e.currentTarget.setAttribute("aria-expanded",String(opening))}window.toggleEventMenu=toggleEventMenu;
function togglePersonMenu(e,id){e.stopPropagation();const menu=$("#person-menu-"+id),opening=menu.hidden;$$(".person-menu").forEach(x=>x.hidden=true);menu.hidden=!opening}window.togglePersonMenu=togglePersonMenu;
async function editEvent(id){try{const data=await request(`/api/events/${id}`);pendingEvent={id:data.event.id,title:data.event.title,eventDate:data.event.date,cityId:Number(data.event.cityId),note:data.event.note||""};attendanceExisting=new Set(data.personIds.map(Number));attendanceSelected=new Set(data.personIds.map(Number));$("#attendanceSearch").value="";$("#visitNote").value=data.event.note||"";$("#visitDateInput").disabled=false;$("#visitType").disabled=false;$("#visitCustomType").disabled=false;setVisitType(data.event.title);$("#visitTitle").textContent="Редактировать встречу";setVisitDate(data.event.date);renderChecks();$("#visitDialog").showModal()}catch(error){toast(friendlyError(error))}}window.editEvent=editEvent;
async function showEventAttendees(e,id,kind){e.stopPropagation();try{const data=await request(`/api/events/${id}`),labels={all:"Все участники",new:"Новенькие",repeat:"Пришли повторно"},list=data.attendees.filter(p=>kind==="all"||(kind==="new"?Number(p.isNew)===1:Number(p.isNew)!==1));$("#attendeeDetailsTitle").textContent=labels[kind];$("#attendeeDetailsMeta").textContent=`${data.event.title} · ${new Date(data.event.date).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}`;$("#attendeeDetailsList").innerHTML=list.map(p=>`<div class="attendee-row"><div class="av ${av(p.id)}">${initials(p)}</div><span><b>${p.first} ${p.last||""}</b><small>${Number(p.isNew)===1?"Первое посещение":"Повторное посещение"}</small></span></div>`).join("")||'<div class="empty">В этой категории никого нет</div>';$("#attendanceDetailsDialog").showModal()}catch(error){toast(friendlyError(error))}}window.showEventAttendees=showEventAttendees;
async function deleteEvent(id){if(!confirm("Удалить встречу и связанные отметки посещения?"))return;try{await request(`/api/events/${id}`,{method:"DELETE",body:"{}"});toast("Встреча удалена");await load()}catch(error){toast(friendlyError(error))}}window.deleteEvent=deleteEvent;
async function toggleSchedule(cityId,weekday,enabled){try{await request("/api/schedules",{method:"POST",body:JSON.stringify({cityId,weekday,eventType:"Коллективная медитация",enabled})});toast("Расписание обновлено");await load()}catch(e){toast(friendlyError(e))}}
async function updateUser(id,role,cityId){try{await request("/api/users/"+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({role,cityId:cityId||null})});toast("Доступ обновлён");await load()}catch(e){toast(friendlyError(e))}}
async function updateMyRole(role){try{await request("/api/me/profile",{method:"PATCH",body:JSON.stringify({role})});toast("Роль сохранена");await load()}catch(e){toast(friendlyError(e))}}
function openAddPerson(cityId=currentCity,fromAttendance=false){if(!cityId){toast("Сначала выберите город");$("#city").focus();return}editingPersonId=null;addingFromAttendance=fromAttendance;$("#addForm").reset();$("#addForm h2").textContent="Новый человек";$("#newCity").value=String(cityId);$("#acquaintanceDate").value=fromAttendance?$("#visitDateInput").value:new Date().toISOString().slice(0,10);if(fromAttendance)$("#visitDialog").close();$("#addDialog").showModal();setTimeout(()=>$("#first").focus(),0)}
function editPerson(e,id){e.stopPropagation();const p=state.people.find(x=>Number(x.id)===Number(id));if(!p)return;editingPersonId=Number(id);addingFromAttendance=false;$("#addForm").reset();$("#addForm h2").textContent="Редактировать человека";$("#first").value=[p.first,p.last].filter(Boolean).join(" ");$("#contact").value=p.contact||"";$("#newCity").value=String(p.cityId);$("#acquaintanceDate").value=(p.acquaintanceDate||p.created||"").slice(0,10);$("#source").value=p.source||"unknown";$("#photoUrl").value=p.photoUrl||"";$("#practiceStatus").value=["sessions_only","home_regular"].includes(p.practiceStatus)?(p.practiceStatus==="sessions_only"?"sometimes":"daily"):(p.practiceStatus||"unknown");$("#note").value=p.note||"";$("#addDialog").showModal()}window.editPerson=editPerson;
async function deletePerson(e,id){e.stopPropagation();const p=state.people.find(x=>Number(x.id)===Number(id));if(!p||!confirm(`Удалить ${p.first} ${p.last||""} и всю историю этого человека?`))return;try{await request(`/api/people/${id}`,{method:"DELETE",body:"{}"});toast("Человек удалён");await load(currentCity)}catch(error){toast(friendlyError(error))}}window.deletePerson=deletePerson;
function closeAddPerson(){const reopen=addingFromAttendance;addingFromAttendance=false;$("#addDialog").close();if(reopen){renderChecks();$("#visitDialog").showModal()}}
$$("[data-view]").forEach(b=>b.onclick=()=>go(b.dataset.view));document.addEventListener("click",e=>{$$(".event-menu,.person-menu").forEach(x=>x.hidden=true);$$(".event-more").forEach(x=>x.setAttribute("aria-expanded","false"));const p=e.target.closest("[data-person]");if(p)showProfile(p.dataset.person)});$("#city").onchange=async e=>{currentCity=e.target.value;try{await request("/api/me/preferences",{method:"PATCH",body:JSON.stringify({cityId:currentCity||null})});await load(currentCity)}catch(error){toast(friendlyError(error))}};$("#search").oninput=renderPeople;$("#filter").onchange=renderPeople;$("#attendanceSearch").oninput=renderChecks;$("#visitDateInput").onchange=e=>{const date=new Date(e.target.value+"T12:00:00");pendingEvent.eventDate=date.toISOString();$("#visitDate").textContent=date.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})};$("#visitType").onchange=()=>{const custom=$("#visitType").value==="Другое";$("#visitCustomType").hidden=!custom;if(custom)$("#visitCustomType").focus();syncVisitType()};$("#visitCustomType").oninput=syncVisitType;$("#myRole").onchange=e=>updateMyRole(e.target.value);$("#attendanceAddPerson").onclick=()=>openAddPerson(pendingEvent.cityId,true);$("#saveInitialCity").onclick=saveInitialCity;$("#cityOnboardingDialog").addEventListener("cancel",event=>event.preventDefault());
$$("[data-add]").forEach(b=>b.onclick=()=>openAddPerson(currentCity,false));$$("[data-attendance]").forEach(b=>b.onclick=()=>openAttendance());$$("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());$$("[data-close-add]").forEach(b=>b.onclick=closeAddPerson);
$("#addForm").onsubmit=async e=>{e.preventDefault();const submit=e.submitter||e.target.querySelector('button[type="submit"]');submit.disabled=true;try{const payload={first:$("#first").value.trim(),last:"",contact:$("#contact").value.trim(),note:$("#note").value.trim(),photoUrl:$("#photoUrl").value.trim(),practiceStatus:$("#practiceStatus").value,cityId:Number($("#newCity").value),acquaintanceDate:$("#acquaintanceDate").value||new Date().toISOString().slice(0,10),source:$("#source").value};const isEdit=Boolean(editingPersonId),result=await request(isEdit?`/api/people/${editingPersonId}`:"/api/people/new",{method:isEdit?"PATCH":"POST",body:JSON.stringify(payload)}),reopen=!isEdit&&addingFromAttendance;addingFromAttendance=false;editingPersonId=null;if(reopen)attendanceSelected.add(Number(result.id));e.target.reset();$("#addDialog").close();toast(isEdit?"Карточка обновлена":reopen?"Новый участник добавлен и отмечен":"Человек добавлен");await load(currentCity);if(reopen){renderChecks();$("#visitDialog").showModal()}}catch(err){toast(friendlyError(err))}finally{submit.disabled=false}};
$("#contactForm").onsubmit=async e=>{e.preventDefault();const id=$("#contactPersonId").value;try{await request(`/api/people/${id}/contact`,{method:"POST",body:JSON.stringify({type:$("#contactType").value,note:$("#contactNote").value})});$("#contactDialog").close();toast("Контакт сохранён в истории");await load()}catch(err){toast(friendlyError(err))}};
$("#saveVisit").onclick=async()=>{const ids=[...attendanceSelected];syncVisitType();pendingEvent.note=$("#visitNote").value.trim();try{if(pendingEvent.id){await request(`/api/events/${pendingEvent.id}`,{method:"PATCH",body:JSON.stringify({...pendingEvent,personIds:ids})});toast("Встреча обновлена")}else{await request("/api/events",{method:"POST",body:JSON.stringify({...pendingEvent,personIds:ids})});toast(`Отмечено участников: ${ids.length}`)}$("#visitDialog").close();await load()}catch(error){toast(friendlyError(error))}};
function exportExcel(){const rows=[["Имя","Фамилия","Город","Телефон/соцсеть","Откуда узнал","Статус посещений","Домашняя практика","Всего посещений","За 30 дней","Последнее занятие","Последний контакт","Комментарий"],...state.people.map(p=>[p.first,p.last,cityName(p.cityId),p.contact,sourceLabels[p.source]||sourceLabels.unknown,attendanceStatus(p).text,practiceLabels[p.practiceStatus],p.visits,p.recentVisits,Number(p.visits)>0?new Date(p.lastVisit).toLocaleDateString("ru-RU"):"—",p.lastContact?new Date(p.lastContact).toLocaleDateString("ru-RU"):"—",p.note])],csv="\ufeff"+rows.map(r=>r.map(v=>`"${String(v||"").replaceAll('"','""')}"`).join(";")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`Ananda_Prachar_${cityName(currentCity)}_${new Date().toISOString().slice(0,10)}.csv`;a.click();toast("Файл сохранён в папку «Загрузки»")}
$("#exportPeople")?.addEventListener("click",exportExcel);$("#exportAnalytics")?.addEventListener("click",exportExcel);$("#logoutApp")?.addEventListener("click",async()=>{await request("/api/auth/logout",{method:"POST",body:"{}"});location.reload()});$("#teamAddCity")?.addEventListener("click",async()=>{const name=prompt("Название города или посёлка");if(!name?.trim())return;try{const result=await request("/api/cities",{method:"POST",body:JSON.stringify({name:name.trim()})});currentCity=String(result.id);await request("/api/me/preferences",{method:"PATCH",body:JSON.stringify({cityId:result.id})});toast("Населённый пункт добавлен");await load(currentCity)}catch(e){toast(friendlyError(e))}});$$("[data-period]").forEach(b=>b.onclick=()=>{$$("[data-period]").forEach(x=>x.classList.remove("active"));b.classList.add("active");period=Number(b.dataset.period);renderAnalytics()});
function renderPasswordUpdate(){document.body.innerHTML=`<main class="login"><div class="brand"><span class="brand-mark">AP</span><b>Ananda Prachar</b></div><h1>Новый пароль</h1><p class="lead">Придумайте новый пароль длиной не меньше 8 символов.</p><form id="passwordForm" class="auth-form"><label>Новый пароль<input id="newPassword" type="password" minlength="8" autocomplete="new-password" required></label><p id="authError" class="auth-error" hidden></p><button class="primary" type="submit">Сохранить пароль</button></form></main>`;$("#passwordForm").onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await request("/api/auth/password",{method:"PATCH",body:JSON.stringify({password:$("#newPassword").value})});document.querySelector(".lead").textContent="Пароль сохранён. Открываем приложение…";$("#passwordForm").hidden=true;history.replaceState(null,"",location.pathname);setTimeout(()=>location.reload(),900)}catch(error){$("#authError").textContent=friendlyError(error);$("#authError").hidden=false;button.disabled=false}}}
window.addEventListener("ananda-password-recovery",renderPasswordUpdate);
window.addEventListener("error",event=>{console.error("Ananda Prachar:",event.error||event.message)});
window.addEventListener("unhandledrejection",event=>{console.error("Ananda Prachar:",event.reason)});
function registerAgentTools(){const mc=document.modelContext;if(!mc?.registerTool)return;Promise.resolve(mc.registerTool({name:"add_person",title:"Добавить человека",description:"Добавляет человека в базу выбранного города.",inputSchema:{type:"object",properties:{first:{type:"string"},last:{type:"string"},contact:{type:"string"},note:{type:"string"},cityId:{type:"integer"}},required:["first","cityId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const result=await request("/api/people",{method:"POST",body:JSON.stringify(input)});await load();return{id:result.id,status:"created"}}})).catch(()=>{})}
let installPrompt=null;window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;$("#installApp").hidden=false});$("#installApp")?.addEventListener("click",async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#installApp").hidden=true}else toast("На iPhone: Поделиться → На экран Домой")});async function enableAutomaticUpdates(){if(!("serviceWorker" in navigator))return;let reloading=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloading)return;reloading=true;location.reload()});try{const registration=await navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"});await registration.update();setInterval(()=>registration.update().catch(()=>{}),30*60*1000);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")registration.update().catch(()=>{})})}catch(error){console.warn("Не удалось проверить обновление приложения",error)}}const canonicalUrl=new URL(location.href);if(canonicalUrl.searchParams.has("v")){canonicalUrl.searchParams.delete("v");history.replaceState(null,"",canonicalUrl.pathname+(canonicalUrl.search||"")+(canonicalUrl.hash||""))}enableAutomaticUpdates();const firstView=location.hash.slice(1);if(firstView&&document.getElementById(firstView))go(firstView);registerAgentTools();if(window.authRecovery||location.hash.includes("type=recovery"))renderPasswordUpdate();else load();
