-- Ananda Prachar. Выполните этот файл один раз в Supabase SQL Editor.
create table if not exists public.cities (
 id bigint generated by default as identity primary key, name text not null unique,
 region text not null default 'Россия', active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade, email text, name text,
 role text not null default 'city_member' check(role in('city_member','city_admin','national_admin')),
 city_id bigint references public.cities(id) on delete set null,
 preferred_city_id bigint references public.cities(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.people (
 id bigint generated by default as identity primary key,
 city_id bigint not null references public.cities(id) on delete restrict,
 first_name text not null check(char_length(trim(first_name))>0), last_name text not null default '',
 contact text not null default '', note text not null default '', source text not null default 'unknown',
 acquaintance_date date, photo_url text not null default '', practice_status text not null default 'unknown',
 last_visit timestamptz, last_contact timestamptz, visits integer not null default 0 check(visits>=0),
 created_by uuid references public.profiles(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.events (
 id bigint generated by default as identity primary key,
 city_id bigint not null references public.cities(id) on delete restrict,
 title text not null default 'Коллективная медитация', event_date timestamptz not null,
 created_by uuid references public.profiles(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists events_one_title_per_city_day
 on public.events(city_id,title,((event_date at time zone 'Asia/Yekaterinburg')::date));
create table if not exists public.attendance (
 id bigint generated by default as identity primary key,
 event_id bigint not null references public.events(id) on delete cascade,
 person_id bigint not null references public.people(id) on delete cascade,
 is_new boolean not null default false, created_at timestamptz not null default now(), unique(event_id,person_id)
);
create table if not exists public.interactions (
 id bigint generated by default as identity primary key,
 person_id bigint not null references public.people(id) on delete cascade,
 type text not null default 'message', note text not null default '',
 created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now()
);
create table if not exists public.city_schedules (
 id bigint generated by default as identity primary key,
 city_id bigint not null references public.cities(id) on delete cascade,
 weekday smallint not null check(weekday between 0 and 6),
 event_type text not null default 'Коллективная медитация',
 created_by uuid references public.profiles(id) on delete set null,
 created_at timestamptz not null default now(), unique(city_id,weekday,event_type)
);
create index if not exists people_city_idx on public.people(city_id);
create index if not exists events_city_date_idx on public.events(city_id,event_date desc);
create index if not exists attendance_person_idx on public.attendance(person_id);
create index if not exists interactions_person_date_idx on public.interactions(person_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;
drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists people_touch_updated_at on public.people;
create trigger people_touch_updated_at before update on public.people for each row execute function public.touch_updated_at();
drop trigger if exists events_touch_updated_at on public.events;
create trigger events_touch_updated_at before update on public.events for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
declare initial_role text;
begin
 select case when exists(select 1 from public.profiles) then 'city_member' else 'national_admin' end into initial_role;
 insert into public.profiles(id,email,name,role)
 values(new.id,new.email,coalesce(new.raw_user_meta_data->>'name',split_part(coalesce(new.email,''),'@',1)),initial_role)
 on conflict(id) do nothing;
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_national_admin() returns boolean
language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles where id=auth.uid() and role='national_admin')
$$;
create or replace function public.can_manage_city(target bigint) returns boolean
language sql stable security definer set search_path=public as $$
 select public.is_national_admin() or exists(
  select 1 from public.profiles where id=auth.uid() and coalesce(preferred_city_id,city_id)=target
 )
$$;
grant execute on function public.is_national_admin() to authenticated;
grant execute on function public.can_manage_city(bigint) to authenticated;

alter table public.cities enable row level security;
alter table public.profiles enable row level security;
alter table public.people enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;
alter table public.interactions enable row level security;
alter table public.city_schedules enable row level security;

drop policy if exists cities_read on public.cities;
create policy cities_read on public.cities for select to authenticated using(true);
drop policy if exists cities_add on public.cities;
create policy cities_add on public.cities for insert to authenticated with check(char_length(trim(name)) between 2 and 100);
drop policy if exists cities_admin_change on public.cities;
create policy cities_admin_change on public.cities for update to authenticated using(public.is_national_admin()) with check(public.is_national_admin());
drop policy if exists cities_admin_delete on public.cities;
create policy cities_admin_delete on public.cities for delete to authenticated using(public.is_national_admin());

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated\n using(id=auth.uid() or public.is_national_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated
 using(id=auth.uid()) with check(id=auth.uid() and role in('city_member','city_admin'));
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated
 using(public.is_national_admin()) with check(public.is_national_admin());

drop policy if exists people_read on public.people;
create policy people_read on public.people for select to authenticated using(true);
drop policy if exists people_add on public.people;
create policy people_add on public.people for insert to authenticated with check(public.can_manage_city(city_id));
drop policy if exists people_change on public.people;
create policy people_change on public.people for update to authenticated using(public.can_manage_city(city_id)) with check(public.can_manage_city(city_id));
drop policy if exists people_delete on public.people;
create policy people_delete on public.people for delete to authenticated using(public.can_manage_city(city_id));

drop policy if exists events_read on public.events;
create policy events_read on public.events for select to authenticated using(true);
drop policy if exists events_add on public.events;
create policy events_add on public.events for insert to authenticated with check(public.can_manage_city(city_id));
drop policy if exists events_change on public.events;
create policy events_change on public.events for update to authenticated using(public.can_manage_city(city_id)) with check(public.can_manage_city(city_id));
drop policy if exists events_delete on public.events;
create policy events_delete on public.events for delete to authenticated using(public.can_manage_city(city_id));

drop policy if exists attendance_read on public.attendance;
create policy attendance_read on public.attendance for select to authenticated using(true);
drop policy if exists attendance_add on public.attendance;
create policy attendance_add on public.attendance for insert to authenticated with check(
 exists(select 1 from public.events e where e.id=event_id and public.can_manage_city(e.city_id))
);
drop policy if exists attendance_delete on public.attendance;
create policy attendance_delete on public.attendance for delete to authenticated using(
 exists(select 1 from public.events e where e.id=event_id and public.can_manage_city(e.city_id))
);

drop policy if exists interactions_read on public.interactions;
create policy interactions_read on public.interactions for select to authenticated using(true);
drop policy if exists interactions_add on public.interactions;
create policy interactions_add on public.interactions for insert to authenticated with check(
 exists(select 1 from public.people p where p.id=person_id and public.can_manage_city(p.city_id))
);
drop policy if exists interactions_change on public.interactions;
create policy interactions_change on public.interactions for update to authenticated
 using(exists(select 1 from public.people p where p.id=person_id and public.can_manage_city(p.city_id)))
 with check(exists(select 1 from public.people p where p.id=person_id and public.can_manage_city(p.city_id)));
drop policy if exists interactions_delete on public.interactions;
create policy interactions_delete on public.interactions for delete to authenticated using(
 exists(select 1 from public.people p where p.id=person_id and public.can_manage_city(p.city_id))
);

drop policy if exists schedules_read on public.city_schedules;
create policy schedules_read on public.city_schedules for select to authenticated using(true);
drop policy if exists schedules_add on public.city_schedules;
create policy schedules_add on public.city_schedules for insert to authenticated with check(public.can_manage_city(city_id));
drop policy if exists schedules_change on public.city_schedules;
create policy schedules_change on public.city_schedules for update to authenticated using(public.can_manage_city(city_id)) with check(public.can_manage_city(city_id));
drop policy if exists schedules_delete on public.city_schedules;
create policy schedules_delete on public.city_schedules for delete to authenticated using(public.can_manage_city(city_id));

grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
insert into public.cities(name) values
('Пермь'),('Екатеринбург'),('Златоуст'),('Челябинск'),('Магнитогорск'),('Тюмень'),('Омск')
on conflict(name) do nothing;
