const SUPABASE_URL="https://cxqrrynltflfmfotlhdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_YWuL-KvBLudRYUXYpGJrAQ_xbgY_fx6";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const apiError=(message,status=400,data={})=>Object.assign(new Error(message||"Не удалось выполнить действие"),{status,data});
const parseBody=options=>{try{return options?.body?JSON.parse(options.body):{}}catch{return{}}};
const one=async query=>{const{data,error}=await query;if(error)throw apiError(error.message);return data};
const profileShape=p=>({id:p.id,email:p.email,name:p.name,role:p.role,cityId:p.city_id,preferredCityId:p.preferred_city_id});
const personShape=p=>({id:p.id,first:p.first_name,last:p.last_name,cityId:p.city_id,contact:p.contact,note:p.note,source:p.source,acquaintanceDate:p.acquaintance_date,photoUrl:p.photo_url,practiceStatus:p.practice_status,lastVisit:p.last_visit,lastContact:p.last_contact,visits:p.visits,created:p.created_at,recentVisits:p.recentVisits||0,visitDates:p.visitDates||[],contactCount:p.contactCount||0,lastContactType:p.lastContactType||""});
const eventShape=e=>{const attendance=e.attendance||[];return{id:e.id,cityId:e.city_id,title:e.title,date:e.event_date,total:attendance.length,newcomers:attendance.filter(a=>a.is_new).length,personIds:attendance.map(a=>Number(a.person_id)),newPersonIds:attendance.filter(a=>a.is_new).map(a=>Number(a.person_id)),repeatPersonIds:attendance.filter(a=>!a.is_new).map(a=>Number(a.person_id))}};
const currentAuthUser=async()=>{const{data:{user},error}=await db.auth.getUser();if(error||!user)throw apiError("auth_required",401);return user};
async function currentProfile(){const user=await currentAuthUser();let{data,error}=await db.from("profiles").select("*").eq("id",user.id).maybeSingle();if(error)throw apiError(error.message);if(!data){await new Promise(r=>setTimeout(r,350));({data,error}=await db.from("profiles").select("*").eq("id",user.id).maybeSingle());if(error||!data)throw apiError("Профиль ещё создаётся. Повторите через несколько секунд.",503)}return data}
async function bootstrap(cityId){
 const profile=await currentProfile(),cities=await one(db.from("cities").select("*").eq("active",true).order("name"));
 const city=cityId?Number(cityId):Number(profile.preferred_city_id||profile.city_id||0);
 const peopleQuery=db.from("people").select("*").order("last_visit",{ascending:false});
 const eventsQuery=db.from("events").select("id,city_id,title,event_date,attendance(id,is_new,person_id)").order("event_date",{ascending:false}).limit(500);
 const scheduleQuery=db.from("city_schedules").select("*").order("weekday");
 if(city){peopleQuery.eq("city_id",city);eventsQuery.eq("city_id",city);scheduleQuery.eq("city_id",city)}
 const[peopleRows,eventRows,schedules]=await Promise.all([one(peopleQuery),one(eventsQuery),one(scheduleQuery)]);
 const personIds=peopleRows.map(p=>p.id),visitsByPerson=new Map(),contactsByPerson=new Map();
 if(personIds.length){
  const visits=await one(db.from("attendance").select("person_id,events!inner(event_date)").in("person_id",personIds).gte("events.event_date",new Date(Date.now()-365*864e5).toISOString()));
  visits.forEach(row=>{const id=Number(row.person_id),dates=visitsByPerson.get(id)||[];if(row.events?.event_date)dates.push(row.events.event_date);visitsByPerson.set(id,dates)});
  const contacts=await one(db.from("interactions").select("person_id,type,created_at").in("person_id",personIds).order("created_at",{ascending:false}));
  contacts.forEach(row=>{const id=Number(row.person_id),entry=contactsByPerson.get(id)||{count:0,lastType:""};entry.count++;if(!entry.lastType)entry.lastType=row.type;contactsByPerson.set(id,entry)});
 }
 const people=peopleRows.map(p=>{const dates=visitsByPerson.get(Number(p.id))||[],contact=contactsByPerson.get(Number(p.id))||{count:0,lastType:""};return personShape({...p,visitDates:dates,recentVisits:dates.filter(date=>Date.now()-new Date(date).getTime()<30*864e5).length,contactCount:contact.count,lastContactType:contact.lastType})});
 const events=eventRows.map(eventShape);let users=[];
 if(profile.role==="national_admin")users=(await one(db.from("profiles").select("*").order("created_at"))).map(profileShape);
 return{user:profileShape(profile),cities:cities.map(c=>({id:c.id,name:c.name,region:c.region,active:c.active})),people,events,schedules:schedules.map(s=>({id:s.id,cityId:s.city_id,weekday:s.weekday,eventType:s.event_type})),users}
}
async function history(id){const[visits,contacts]=await Promise.all([one(db.from("attendance").select("events(id,title,event_date,cities(name))").eq("person_id",id)),one(db.from("interactions").select("*").eq("person_id",id).order("created_at",{ascending:false}))]);return{visits:visits.map(v=>({id:v.events.id,title:v.events.title,date:v.events.event_date,city:v.events.cities?.name||""})),contacts:contacts.map(c=>({id:c.id,type:c.type,note:c.note,date:c.created_at,author:""}))}}
async function recalcPerson(id){const rows=await one(db.from("attendance").select("events(event_date)").eq("person_id",id)),dates=rows.map(r=>r.events?.event_date).filter(Boolean).sort().reverse(),patch={visits:rows.length,updated_at:new Date().toISOString()};if(dates[0])patch.last_visit=dates[0];await one(db.from("people").update(patch).eq("id",id))}
async function createEvent(body){const cityId=Number(body.cityId),date=new Date(body.eventDate||Date.now()).toISOString(),day=date.slice(0,10),title=String(body.title||"Коллективная медитация"),existing=await one(db.from("events").select("id,event_date").eq("city_id",cityId).eq("title",title).gte("event_date",day+"T00:00:00.000Z").lte("event_date",day+"T23:59:59.999Z").limit(1));if(existing.length)throw apiError("Эта коллективная медитация уже зарегистрирована. Добавьте людей через меню «•••» у встречи.",409);const user=await currentAuthUser(),event=await one(db.from("events").insert({city_id:cityId,title,event_date:date,created_by:user.id}).select().single()),ids=[...new Set((body.personIds||[]).map(Number))];for(const id of ids){const person=await one(db.from("people").select("id,visits,last_visit").eq("id",id).single());await one(db.from("attendance").insert({event_id:event.id,person_id:id,is_new:Number(person.visits)===0}));await one(db.from("people").update({visits:Number(person.visits)+1,last_visit:!person.last_visit||new Date(person.last_visit)<new Date(date)?date:person.last_visit,updated_at:new Date().toISOString()}).eq("id",id))}return{ok:true,id:event.id}}
async function addEventPeople(id,ids){const event=await one(db.from("events").select("*").eq("id",id).single());let added=0;for(const personId of [...new Set((ids||[]).map(Number))]){const exists=await one(db.from("attendance").select("id").eq("event_id",id).eq("person_id",personId).limit(1));if(exists.length)continue;const person=await one(db.from("people").select("*").eq("id",personId).single());await one(db.from("attendance").insert({event_id:id,person_id:personId,is_new:Number(person.visits)===0}));await one(db.from("people").update({visits:Number(person.visits)+1,last_visit:!person.last_visit||new Date(person.last_visit)<new Date(event.event_date)?event.event_date:person.last_visit,updated_at:new Date().toISOString()}).eq("id",personId));added++}return{ok:true,added}}
async function apiRequest(path,options={}){const method=(options.method||"GET").toUpperCase(),body=parseBody(options),url=new URL(path,location.origin),pathname=url.pathname.replace(/^\/Prachara\/app/,"");
 if(pathname==="/api/auth/register"&&method==="POST"){const{data,error}=await db.auth.signUp({email:String(body.email||"").trim(),password:String(body.password||""),options:{data:{name:String(body.name||"").trim()}}});if(error)throw apiError(error.message,error.status||400);if(!data.session)throw apiError("Подтвердите адрес по ссылке из письма, затем войдите.",202);return{ok:true}}
 if(pathname==="/api/auth/reset"&&method==="POST"){const email=String(body.email||"").trim();if(!email)throw apiError("Укажите электронную почту");const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw apiError(error.message,error.status||400);return{ok:true}}
 if(pathname==="/api/auth/password"&&method==="PATCH"){const password=String(body.password||"");if(password.length<8)throw apiError("Пароль должен содержать не меньше 8 символов");const{error}=await db.auth.updateUser({password});if(error)throw apiError(error.message,error.status||400);return{ok:true}}
 if(pathname==="/api/auth/login"&&method==="POST"){const{error}=await db.auth.signInWithPassword({email:String(body.email||"").trim(),password:String(body.password||"")});if(error)throw apiError("Неверная почта или пароль",401);return{ok:true}}
 if(pathname==="/api/auth/logout"&&method==="POST"){await db.auth.signOut();return{ok:true}}
 if(pathname==="/api/bootstrap"&&method==="GET")return bootstrap(url.searchParams.get("cityId"));
 await currentAuthUser();
 if(pathname==="/api/me/preferences"&&method==="PATCH"){await one(db.from("profiles").update({preferred_city_id:body.cityId||null,city_id:body.cityId||null,updated_at:new Date().toISOString()}).eq("id",(await currentAuthUser()).id));return{ok:true,cityId:body.cityId||null}}
 if(pathname==="/api/me/profile"&&method==="PATCH"){await one(db.from("profiles").update({role:body.role,updated_at:new Date().toISOString()}).eq("id",(await currentAuthUser()).id));return{ok:true,role:body.role}}
 let match=pathname.match(/^\/api\/people\/(\d+)\/history$/);if(match&&method==="GET")return history(Number(match[1]));
 match=pathname.match(/^\/api\/events\/(\d+)$/);if(match&&method==="GET"){const event=await one(db.from("events").select("*").eq("id",Number(match[1])).single()),attendees=await one(db.from("attendance").select("is_new,people(id,first_name,last_name)").eq("event_id",event.id));return{event:{id:event.id,cityId:event.city_id,title:event.title,date:event.event_date},personIds:attendees.map(a=>Number(a.people.id)),attendees:attendees.map(a=>({id:a.people.id,first:a.people.first_name,last:a.people.last_name,isNew:a.is_new?1:0}))}}
 match=pathname.match(/^\/api\/people\/(\d+)$/);if(match&&(method==="PATCH"||method==="DELETE")){const id=Number(match[1]);if(method==="DELETE"){await one(db.from("people").delete().eq("id",id));return{ok:true}}await one(db.from("people").update({first_name:String(body.first||"").trim(),last_name:String(body.last||"").trim(),city_id:Number(body.cityId),contact:String(body.contact||"").trim(),note:String(body.note||"").trim(),source:body.source||"unknown",acquaintance_date:body.acquaintanceDate||null,photo_url:String(body.photoUrl||"").trim(),practice_status:body.practiceStatus||"unknown",updated_at:new Date().toISOString()}).eq("id",id));return{ok:true,id}}
 if((pathname==="/api/people"||pathname==="/api/people/new")&&method==="POST"){const user=await currentAuthUser(),stamp=new Date().toISOString(),has=Boolean(body.hasVisited),person=await one(db.from("people").insert({first_name:String(body.first||"").trim(),last_name:String(body.last||"").trim(),city_id:Number(body.cityId),contact:String(body.contact||"").trim(),note:String(body.note||"").trim(),source:body.source||"unknown",acquaintance_date:body.acquaintanceDate||stamp.slice(0,10),photo_url:String(body.photoUrl||"").trim(),practice_status:body.practiceStatus||"unknown",last_visit:has?stamp:(body.acquaintanceDate||stamp),visits:has?1:0,created_by:user.id}).select().single());return{ok:true,id:person.id}}
 match=pathname.match(/^\/api\/people\/(\d+)\/(visit|contact)$/);if(match&&method==="POST"){const id=Number(match[1]),stamp=new Date().toISOString(),person=await one(db.from("people").select("*").eq("id",id).single());if(match[2]==="visit")await one(db.from("people").update({last_visit:stamp,visits:Number(person.visits)+1,updated_at:stamp}).eq("id",id));else{const user=await currentAuthUser();await one(db.from("people").update({last_contact:stamp,updated_at:stamp}).eq("id",id));await one(db.from("interactions").insert({person_id:id,type:body.type||"message",note:String(body.note||""),created_by:user.id}))}return{ok:true}}
 if(pathname==="/api/events"&&method==="POST")return createEvent(body);
 match=pathname.match(/^\/api\/events\/(\d+)$/);if(match&&method==="PATCH")return addEventPeople(Number(match[1]),body.personIds);
 if(match&&method==="DELETE"){const id=Number(match[1]),rows=await one(db.from("attendance").select("person_id").eq("event_id",id));await one(db.from("events").delete().eq("id",id));for(const row of rows)await recalcPerson(row.person_id);return{ok:true}}
 if(pathname==="/api/schedules"&&method==="POST"){const user=await currentAuthUser();if(body.enabled)await one(db.from("city_schedules").upsert({city_id:Number(body.cityId),weekday:Number(body.weekday),event_type:body.eventType||"Коллективная медитация",created_by:user.id},{onConflict:"city_id,weekday,event_type"}));else await one(db.from("city_schedules").delete().eq("city_id",Number(body.cityId)).eq("weekday",Number(body.weekday)).eq("event_type",body.eventType||"Коллективная медитация"));return{ok:true}}
 if(pathname==="/api/cities"&&method==="POST"){const name=String(body.name||"").trim();let rows=await one(db.from("cities").select("*").eq("name",name).limit(1));if(!rows.length)rows=[await one(db.from("cities").insert({name,region:"Россия",active:true}).select().single())];return{ok:true,id:rows[0].id,name:rows[0].name}}
 match=pathname.match(/^\/api\/users\/(.+)$/);if(match&&method==="PATCH"){await one(db.from("profiles").update({role:body.role,city_id:body.cityId||null,preferred_city_id:body.cityId||null,updated_at:new Date().toISOString()}).eq("id",decodeURIComponent(match[1])));return{ok:true}}
 throw apiError("Маршрут не найден",404)
}
window.apiRequest=apiRequest;

window.authRecovery=false;
db.auth.onAuthStateChange(event=>{if(event==="PASSWORD_RECOVERY"){window.authRecovery=true;window.dispatchEvent(new Event("ananda-password-recovery"))}});
