const SUPABASE_URL="https://cxqrrynltflfmfotlhdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_YWuL-KvBLudRYUXYpGJrAQ_xbgY_fx6";
const DISMISSED_PREFIX="__schedule_dismissed__:";

const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const apiError=(message,status=400,data={})=>Object.assign(new Error(message||"Не удалось выполнить действие"),{status,data});
const parseBody=options=>{try{return options?.body?JSON.parse(options.body):{}}catch{return{}}};
const one=async query=>{const{data,error}=await query;if(error)throw apiError(error.message);return data};
const profileShape=p=>({id:p.id,email:p.email,name:p.name,role:p.role,cityId:p.city_id,preferredCityId:p.preferred_city_id});
const personShape=p=>({id:p.id,first:p.first_name,last:p.last_name,cityId:p.city_id,contact:p.contact,note:p.note,source:p.source,acquaintanceDate:p.acquaintance_date,photoUrl:p.photo_url,practiceStatus:p.practice_status,lastVisit:p.last_visit,lastContact:p.last_contact,visits:p.visits,created:p.created_at,recentVisits:p.recentVisits||0,visitDates:p.visitDates||[],contactCount:p.contactCount||0,lastContactType:p.lastContactType||"",achievements:p.achievements||{},careState:p.care_state||"auto",careBarriers:p.care_barriers||[],careMotivations:p.care_motivations||[],careNote:p.care_note||"",careNextStep:p.care_next_step||"",careNextContactAt:p.care_next_contact_at||null,careTasks:p.careTasks||[],careEvents:p.careEvents||[]});
const eventShape=e=>{const attendance=e.attendance||[];return{id:e.id,cityId:e.city_id,title:e.title,note:e.note||"",date:e.event_date,total:attendance.length,newcomers:attendance.filter(a=>a.is_new).length,personIds:attendance.map(a=>Number(a.person_id)),newPersonIds:attendance.filter(a=>a.is_new).map(a=>Number(a.person_id)),repeatPersonIds:attendance.filter(a=>!a.is_new).map(a=>Number(a.person_id))}};
const DEFAULT_CARE_SETTINGS={feedbackHours:4,reminderHours:24,firstAbsenceDays:7,secondAbsenceDays:14,reactivationDays:30,activeReturnVisits:3,templates:{}};
const careSettingsShape=s=>s?{cityId:s.city_id,feedbackHours:s.feedback_hours,reminderHours:s.reminder_hours,firstAbsenceDays:s.first_absence_days,secondAbsenceDays:s.second_absence_days,reactivationDays:s.reactivation_days,activeReturnVisits:s.active_return_visits,templates:s.templates||{}}:{...DEFAULT_CARE_SETTINGS};
const careTaskShape=t=>({id:t.id,personId:t.person_id,sourceKey:t.source_key,type:t.task_type,dueAt:t.due_at,status:t.status,priority:t.priority,snoozedUntil:t.snoozed_until,completedAt:t.completed_at,result:t.result||""});
const careEventShape=e=>({id:e.id,personId:e.person_id,type:e.event_type,comment:e.comment||"",result:e.result||"",state:e.state||"",nextStep:e.next_step||"",dueAt:e.due_at,metadata:e.metadata||{},author:e.author_name||"",date:e.created_at});

const currentAuthUser=async()=>{const{data:{user},error}=await db.auth.getUser();if(error||!user)throw apiError("auth_required",401);return user};
async function currentProfile(){const user=await currentAuthUser();let{data,error}=await db.from("profiles").select("*").eq("id",user.id).maybeSingle();if(error)throw apiError(error.message);if(!data){await new Promise(r=>setTimeout(r,350));({data,error}=await db.from("profiles").select("*").eq("id",user.id).maybeSingle());if(error||!data)throw apiError("Профиль ещё создаётся. Повторите через несколько секунд.",503)}return data}
const ACHIEVEMENT_KEYS=new Set(["chat_invited","chat_joined","book_acquired","basic_started","basic_completed","kdi_started","kdi_completed","twice_daily","curator_offered","curator_assigned","acharya_offered","acharya_met","retreat_invited","retreat_attended","mantra_received","initiation_received"]);
async function setAchievement(personId,key,completed=true){if(!ACHIEVEMENT_KEYS.has(key))throw apiError("Неизвестный этап",400);const existing=await one(db.from("interactions").select("id").eq("person_id",personId).eq("type","achievement").eq("note",key));if(completed&&!existing.length){const user=await currentAuthUser();await one(db.from("interactions").insert({person_id:personId,type:"achievement",note:key,created_by:user.id}))}if(!completed&&existing.length)await one(db.from("interactions").delete().eq("person_id",personId).eq("type","achievement").eq("note",key));return{ok:true,key,completed}}
const ensureAchievement=(personId,key)=>setAchievement(personId,key,true);

async function bootstrap(cityId){
 const profile=await currentProfile(),cities=await one(db.from("cities").select("*").eq("active",true).order("name"));
 const city=cityId?Number(cityId):Number(profile.preferred_city_id||profile.city_id||0);
 const peopleQuery=db.from("people").select("*").order("last_visit",{ascending:false}),eventsQuery=db.from("events").select("*,attendance(id,is_new,person_id)").order("event_date",{ascending:false}).limit(500),scheduleQuery=db.from("city_schedules").select("*").order("weekday");
 if(city){peopleQuery.eq("city_id",city);eventsQuery.eq("city_id",city);scheduleQuery.eq("city_id",city)}
 const[peopleRows,eventRows,schedules]=await Promise.all([one(peopleQuery),one(eventsQuery),one(scheduleQuery)]);
 let settingsRow=null;if(city){const{data,error}=await db.from("care_settings").select("*").eq("city_id",city).maybeSingle();if(!error)settingsRow=data}
 const personIds=peopleRows.map(p=>p.id),visitsByPerson=new Map(),contactsByPerson=new Map(),achievementsByPerson=new Map(),tasksByPerson=new Map(),careEventsByPerson=new Map();
 if(personIds.length){
  const[visits,contacts,tasks,careEvents]=await Promise.all([
   one(db.from("attendance").select("person_id,events!inner(event_date)").in("person_id",personIds).gte("events.event_date",new Date(Date.now()-365*864e5).toISOString())),
   one(db.from("interactions").select("person_id,type,note,created_at").in("person_id",personIds).order("created_at",{ascending:false})),
   one(db.from("care_tasks").select("*").in("person_id",personIds).order("updated_at",{ascending:false})),
   one(db.from("care_events").select("*").in("person_id",personIds).order("created_at",{ascending:false}).limit(2000))
  ]);
  visits.forEach(row=>{const id=Number(row.person_id),dates=visitsByPerson.get(id)||[];if(row.events?.event_date)dates.push(row.events.event_date);visitsByPerson.set(id,dates)});
  contacts.forEach(row=>{const id=Number(row.person_id);if(row.type==="achievement"){const entry=achievementsByPerson.get(id)||{};if(row.note&&!entry[row.note])entry[row.note]=row.created_at;achievementsByPerson.set(id,entry);return}const entry=contactsByPerson.get(id)||{count:0,lastType:""};entry.count++;if(!entry.lastType)entry.lastType=row.type;contactsByPerson.set(id,entry)});
  tasks.forEach(row=>{const id=Number(row.person_id),list=tasksByPerson.get(id)||[];list.push(careTaskShape(row));tasksByPerson.set(id,list)});
  careEvents.forEach(row=>{const id=Number(row.person_id),list=careEventsByPerson.get(id)||[];list.push(careEventShape(row));careEventsByPerson.set(id,list)});
 }
 const people=peopleRows.map(p=>{const id=Number(p.id),dates=visitsByPerson.get(id)||[],contact=contactsByPerson.get(id)||{count:0,lastType:""},achievements=achievementsByPerson.get(id)||{};if(["twice_daily","twice_daily_initiation"].includes(p.practice_status)&&!achievements.twice_daily)achievements.twice_daily=p.updated_at||p.created_at;return personShape({...p,visitDates:dates,recentVisits:dates.filter(date=>Date.now()-new Date(date).getTime()<30*864e5).length,contactCount:contact.count,lastContactType:contact.lastType,achievements,careTasks:tasksByPerson.get(id)||[],careEvents:careEventsByPerson.get(id)||[]})});
 const dismissedSchedules=eventRows.filter(e=>String(e.title||"").startsWith(DISMISSED_PREFIX)).map(e=>({cityId:e.city_id,eventType:String(e.title).slice(DISMISSED_PREFIX.length),date:e.event_date})),events=eventRows.filter(e=>!String(e.title||"").startsWith(DISMISSED_PREFIX)).map(eventShape);let users=[];if(profile.role==="national_admin")users=(await one(db.from("profiles").select("*").order("created_at"))).map(profileShape);
 return{user:profileShape(profile),cities:cities.map(c=>({id:c.id,name:c.name,region:c.region,active:c.active})),people,events,schedules:schedules.map(s=>({id:s.id,cityId:s.city_id,weekday:s.weekday,eventType:s.event_type})),dismissedSchedules,careSettings:careSettingsShape(settingsRow),users}
}
async function history(id){const[visits,contacts,careEvents]=await Promise.all([one(db.from("attendance").select("events(id,title,event_date,cities(name))").eq("person_id",id)),one(db.from("interactions").select("*").eq("person_id",id).order("created_at",{ascending:false})),one(db.from("care_events").select("*").eq("person_id",id).order("created_at",{ascending:false}))]);return{visits:visits.map(v=>({id:v.events.id,title:v.events.title,date:v.events.event_date,city:v.events.cities?.name||""})),contacts:contacts.filter(c=>c.type!=="achievement").map(c=>({id:c.id,type:c.type,note:c.note,date:c.created_at,author:""})),careEvents:careEvents.map(careEventShape)}}
async function recalcPerson(id){const rows=await one(db.from("attendance").select("events(event_date)").eq("person_id",id)),dates=rows.map(r=>r.events?.event_date).filter(Boolean).sort().reverse(),patch={visits:rows.length,last_visit:dates[0]||null,updated_at:new Date().toISOString()};await one(db.from("people").update(patch).eq("id",id))}
async function createEvent(body){const cityId=Number(body.cityId),date=new Date(body.eventDate||Date.now()).toISOString(),day=date.slice(0,10),title=String(body.title||"Коллективная медитация"),existing=await one(db.from("events").select("id,event_date").eq("city_id",cityId).eq("title",title).gte("event_date",day+"T00:00:00.000Z").lte("event_date",day+"T23:59:59.999Z").limit(1));if(existing.length)throw apiError("Эта коллективная медитация уже зарегистрирована. Добавьте людей через меню «•••» у встречи.",409);const user=await currentAuthUser(),eventPayload={city_id:cityId,title,event_date:date,created_by:user.id,note:String(body.note||"").trim()};let event;{let{data,error}=await db.from("events").insert(eventPayload).select().single();if(error&&/note.*column|column.*note/i.test(error.message||""))({data,error}=await db.from("events").insert({city_id:cityId,title,event_date:date,created_by:user.id}).select().single());if(error)throw apiError(error.message);event=data}const ids=[...new Set((body.personIds||[]).map(Number))];for(const id of ids){const person=await one(db.from("people").select("id,visits,last_visit").eq("id",id).single());await one(db.from("attendance").insert({event_id:event.id,person_id:id,is_new:Number(person.visits)===0}));await one(db.from("people").update({visits:Number(person.visits)+1,last_visit:!person.last_visit||new Date(person.last_visit)<new Date(date)?date:person.last_visit,updated_at:new Date().toISOString()}).eq("id",id));if(/ретрит/i.test(title))await ensureAchievement(id,"retreat_attended")}return{ok:true,id:event.id}}
async function updateEvent(id,body){const current=await one(db.from("events").select("*").eq("id",id).single()),title=String(body.title||current.title||"Коллективная медитация").trim(),date=new Date(body.eventDate||current.event_date).toISOString(),day=date.slice(0,10),duplicates=await one(db.from("events").select("id").eq("city_id",current.city_id).eq("title",title).gte("event_date",day+"T00:00:00.000Z").lte("event_date",day+"T23:59:59.999Z").neq("id",id).limit(1));if(duplicates.length)throw apiError("Такая встреча в этот день уже зарегистрирована.",409);const rows=await one(db.from("attendance").select("id,person_id").eq("event_id",id)),currentIds=new Set(rows.map(r=>Number(r.person_id))),desiredIds=new Set((body.personIds||[]).map(Number)),removed=rows.filter(r=>!desiredIds.has(Number(r.person_id))),added=[...desiredIds].filter(personId=>!currentIds.has(personId));{const patch={title,event_date:date,note:String(body.note||"").trim(),updated_at:new Date().toISOString()};let{error}=await db.from("events").update(patch).eq("id",id);if(error&&/note.*column|column.*note/i.test(error.message||""))({error}=await db.from("events").update({title,event_date:date,updated_at:patch.updated_at}).eq("id",id));if(error)throw apiError(error.message)}if(removed.length)await one(db.from("attendance").delete().in("id",removed.map(r=>r.id)));for(const personId of added){const person=await one(db.from("people").select("id,visits").eq("id",personId).single());await one(db.from("attendance").insert({event_id:id,person_id:personId,is_new:Number(person.visits)===0}))}const affected=new Set([...rows.map(r=>Number(r.person_id)),...added]);for(const personId of affected)await recalcPerson(personId);if(/ретрит/i.test(title))for(const personId of desiredIds)await ensureAchievement(personId,"retreat_attended");return{ok:true,added:added.length,removed:removed.length}}
async function apiRequest(path,options={}){const method=(options.method||"GET").toUpperCase(),body=parseBody(options),url=new URL(path,location.origin),pathname=url.pathname.replace(/^\/Prachara\/app/,"");
 if(pathname==="/api/auth/register"&&method==="POST"){const{data,error}=await db.auth.signUp({email:String(body.email||"").trim(),password:String(body.password||""),options:{data:{name:String(body.name||"").trim()}}});if(error)throw apiError(error.message,error.status||400);if(!data.session)throw apiError("Подтвердите адрес по ссылке из письма, затем войдите.",202);return{ok:true}}
 if(pathname==="/api/auth/reset"&&method==="POST"){const email=String(body.email||"").trim();if(!email)throw apiError("Укажите электронную почту");const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw apiError(error.message,error.status||400);return{ok:true}}
 if(pathname==="/api/auth/password"&&method==="PATCH"){const password=String(body.password||"");if(password.length<8)throw apiError("Пароль должен содержать не меньше 8 символов");const{error}=await db.auth.updateUser({password});if(error)throw apiError(error.message,error.status||400);return{ok:true}}
 if(pathname==="/api/auth/login"&&method==="POST"){const{error}=await db.auth.signInWithPassword({email:String(body.email||"").trim(),password:String(body.password||"")});if(error)throw apiError("Неверная почта или пароль",401);return{ok:true}}
 if(pathname==="/api/auth/logout"&&method==="POST"){await db.auth.signOut();return{ok:true}}
 if(pathname==="/api/bootstrap"&&method==="GET")return bootstrap(url.searchParams.get("cityId"));
 await currentAuthUser();
 if(pathname==="/api/me/preferences"&&method==="PATCH"){await one(db.from("profiles").update({preferred_city_id:body.cityId||null,city_id:body.cityId||null,updated_at:new Date().toISOString()}).eq("id",(await currentAuthUser()).id));return{ok:true,cityId:body.cityId||null}}
 if(pathname==="/api/me/profile"&&method==="PATCH"){await one(db.from("profiles").update({role:body.role,updated_at:new Date().toISOString()}).eq("id",(await currentAuthUser()).id));return{ok:true,role:body.role}}
 if(pathname==="/api/care/settings"&&method==="PATCH"){const user=await currentAuthUser(),cityId=Number(body.cityId),payload={city_id:cityId,feedback_hours:Number(body.feedbackHours)||4,reminder_hours:Number(body.reminderHours)||24,first_absence_days:Number(body.firstAbsenceDays)||7,second_absence_days:Number(body.secondAbsenceDays)||14,reactivation_days:Number(body.reactivationDays)||30,active_return_visits:Number(body.activeReturnVisits)||3,templates:body.templates||{},updated_by:user.id,updated_at:new Date().toISOString()};await one(db.from("care_settings").upsert(payload,{onConflict:"city_id"}));return{ok:true}}
 if(pathname==="/api/care/events"&&method==="POST"){const user=await currentAuthUser(),profile=await currentProfile(),personId=Number(body.personId),stamp=new Date().toISOString(),eventType=String(body.eventType||"other"),payload={person_id:personId,event_type:eventType,comment:String(body.comment||""),result:String(body.result||""),state:String(body.state||""),next_step:String(body.nextStep||""),due_at:body.dueAt||null,metadata:body.metadata||{},author_name:profile.name||profile.email||"",created_by:user.id};await one(db.from("care_events").insert(payload));const patch={updated_at:stamp};if(body.state)patch.care_state=body.state;if(body.nextStep!==undefined)patch.care_next_step=String(body.nextStep||"");if(body.dueAt!==undefined)patch.care_next_contact_at=body.dueAt||null;if(["message_sent","feedback","reactivation","diagnostic_contact"].includes(eventType)){patch.last_contact=stamp;await one(db.from("interactions").insert({person_id:personId,type:eventType==="feedback"?"feedback":"message",note:String(body.comment||body.result||""),created_by:user.id}))}await one(db.from("people").update(patch).eq("id",personId));if(body.sourceKey)await one(db.from("care_tasks").upsert({person_id:personId,source_key:String(body.sourceKey),task_type:eventType,status:"completed",priority:body.priority||"medium",completed_at:stamp,result:String(body.result||""),created_by:user.id,updated_at:stamp},{onConflict:"person_id,source_key"}));return{ok:true}}
 let careMatch=pathname.match(/^\/api\/care\/profile\/(\d+)$/);if(careMatch&&method==="PATCH"){const id=Number(careMatch[1]),user=await currentAuthUser(),profile=await currentProfile(),patch={care_state:body.state||"auto",care_barriers:Array.isArray(body.barriers)?body.barriers:[],care_motivations:Array.isArray(body.motivations)?body.motivations:[],care_note:String(body.note||""),care_next_step:String(body.nextStep||""),care_next_contact_at:body.nextContactAt||null,updated_at:new Date().toISOString()};await one(db.from("people").update(patch).eq("id",id));await one(db.from("care_events").insert({person_id:id,event_type:"profile_updated",comment:"Обновлены данные заботы",state:patch.care_state,next_step:patch.care_next_step,due_at:patch.care_next_contact_at,author_name:profile.name||profile.email||"",created_by:user.id}));return{ok:true}}
 careMatch=pathname.match(/^\/api\/care\/tasks\/(\d+)$/);if(careMatch&&method==="POST"){const personId=Number(careMatch[1]),user=await currentAuthUser(),stamp=new Date().toISOString(),payload={person_id:personId,source_key:String(body.sourceKey),task_type:String(body.taskType||"individual"),status:String(body.status||"open"),priority:String(body.priority||"medium"),snoozed_until:body.snoozedUntil||null,completed_at:body.status==="completed"?stamp:null,result:String(body.result||""),created_by:user.id,updated_at:stamp};await one(db.from("care_tasks").upsert(payload,{onConflict:"person_id,source_key"}));return{ok:true}}
 let match=pathname.match(/^\/api\/people\/(\d+)\/achievement$/);if(match&&method==="POST")return setAchievement(Number(match[1]),String(body.key||""),Boolean(body.completed));
 match=pathname.match(/^\/api\/people\/(\d+)\/history$/);if(match&&method==="GET")return history(Number(match[1]));
 match=pathname.match(/^\/api\/events\/(\d+)$/);if(match&&method==="GET"){const event=await one(db.from("events").select("*").eq("id",Number(match[1])).single()),attendees=await one(db.from("attendance").select("is_new,people(id,first_name,last_name)").eq("event_id",event.id));return{event:{id:event.id,cityId:event.city_id,title:event.title,note:event.note||"",date:event.event_date},personIds:attendees.map(a=>Number(a.people.id)),attendees:attendees.map(a=>({id:a.people.id,first:a.people.first_name,last:a.people.last_name,isNew:a.is_new?1:0}))}}
 match=pathname.match(/^\/api\/people\/(\d+)$/);if(match&&(method==="PATCH"||method==="DELETE")){const id=Number(match[1]);if(method==="DELETE"){await one(db.from("people").delete().eq("id",id));return{ok:true}}await one(db.from("people").update({first_name:String(body.first||"").trim(),last_name:String(body.last||"").trim(),city_id:Number(body.cityId),contact:String(body.contact||"").trim(),note:String(body.note||"").trim(),source:body.source||"unknown",acquaintance_date:body.acquaintanceDate||null,photo_url:String(body.photoUrl||"").trim(),practice_status:body.practiceStatus||"unknown",updated_at:new Date().toISOString()}).eq("id",id));if(["twice_daily","twice_daily_initiation"].includes(body.practiceStatus))await ensureAchievement(id,"twice_daily");return{ok:true,id}}
 if((pathname==="/api/people"||pathname==="/api/people/new")&&method==="POST"){const user=await currentAuthUser(),stamp=new Date().toISOString(),has=Boolean(body.hasVisited),person=await one(db.from("people").insert({first_name:String(body.first||"").trim(),last_name:String(body.last||"").trim(),city_id:Number(body.cityId),contact:String(body.contact||"").trim(),note:String(body.note||"").trim(),source:body.source||"unknown",acquaintance_date:body.acquaintanceDate||stamp.slice(0,10),photo_url:String(body.photoUrl||"").trim(),practice_status:body.practiceStatus||"unknown",last_visit:has?stamp:(body.acquaintanceDate||stamp),visits:has?1:0,created_by:user.id}).select().single());if(["twice_daily","twice_daily_initiation"].includes(body.practiceStatus))await ensureAchievement(person.id,"twice_daily");return{ok:true,id:person.id}}
 match=pathname.match(/^\/api\/people\/(\d+)\/(visit|contact)$/);if(match&&method==="POST"){const id=Number(match[1]),stamp=new Date().toISOString(),person=await one(db.from("people").select("*").eq("id",id).single());if(match[2]==="visit")await one(db.from("people").update({last_visit:stamp,visits:Number(person.visits)+1,updated_at:stamp}).eq("id",id));else{const user=await currentAuthUser(),profile=await currentProfile();await one(db.from("people").update({last_contact:stamp,care_next_step:String(body.nextStep||""),care_next_contact_at:body.nextContactAt||null,care_state:body.state||person.care_state||"auto",updated_at:stamp}).eq("id",id));await one(db.from("interactions").insert({person_id:id,type:body.type||"message",note:String(body.note||""),created_by:user.id}));await one(db.from("care_events").insert({person_id:id,event_type:body.eventType||"message_sent",comment:String(body.note||""),result:String(body.result||""),state:body.state||"",next_step:String(body.nextStep||""),due_at:body.nextContactAt||null,author_name:profile.name||profile.email||"",created_by:user.id}));if(body.sourceKey)await one(db.from("care_tasks").upsert({person_id:id,source_key:String(body.sourceKey),task_type:body.eventType||"message_sent",status:"completed",priority:body.priority||"medium",completed_at:stamp,result:String(body.result||""),created_by:user.id,updated_at:stamp},{onConflict:"person_id,source_key"}))}return{ok:true}}
 if(pathname==="/api/events"&&method==="POST")return createEvent(body);
 match=pathname.match(/^\/api\/events\/(\d+)$/);if(match&&method==="PATCH")return updateEvent(Number(match[1]),body);
 if(match&&method==="DELETE"){const id=Number(match[1]),rows=await one(db.from("attendance").select("person_id").eq("event_id",id));await one(db.from("events").delete().eq("id",id));for(const row of rows)await recalcPerson(row.person_id);return{ok:true}}
 if(pathname==="/api/schedules/dismiss"&&method==="POST"){const user=await currentAuthUser(),cityId=Number(body.cityId),title=String(body.title||"Коллективная медитация").trim(),date=new Date(body.date||Date.now()).toISOString(),day=date.slice(0,10),marker=DISMISSED_PREFIX+title,existing=await one(db.from("events").select("id").eq("city_id",cityId).eq("title",marker).gte("event_date",day+"T00:00:00.000Z").lte("event_date",day+"T23:59:59.999Z").limit(1));if(!existing.length){const payload={city_id:cityId,title:marker,event_date:date,created_by:user.id,note:"Встреча не состоялась"};let{error}=await db.from("events").insert(payload);if(error&&/note.*column|column.*note/i.test(error.message||""))({error}=await db.from("events").insert({city_id:cityId,title:marker,event_date:date,created_by:user.id}));if(error)throw apiError(error.message)}return{ok:true}}
 if(pathname==="/api/schedules"&&method==="POST"){const user=await currentAuthUser();if(body.enabled)await one(db.from("city_schedules").upsert({city_id:Number(body.cityId),weekday:Number(body.weekday),event_type:body.eventType||"Коллективная медитация",created_by:user.id},{onConflict:"city_id,weekday,event_type"}));else await one(db.from("city_schedules").delete().eq("city_id",Number(body.cityId)).eq("weekday",Number(body.weekday)).eq("event_type",body.eventType||"Коллективная медитация"));return{ok:true}}
 if(pathname==="/api/cities"&&method==="POST"){const name=String(body.name||"").trim();let rows=await one(db.from("cities").select("*").eq("name",name).limit(1));if(!rows.length)rows=[await one(db.from("cities").insert({name,region:"Россия",active:true}).select().single())];return{ok:true,id:rows[0].id,name:rows[0].name}}
 match=pathname.match(/^\/api\/users\/(.+)$/);if(match&&method==="PATCH"){await one(db.from("profiles").update({role:body.role,city_id:body.cityId||null,preferred_city_id:body.cityId||null,updated_at:new Date().toISOString()}).eq("id",decodeURIComponent(match[1])));return{ok:true}}
 throw apiError("Маршрут не найден",404)
}
window.apiRequest=apiRequest;

window.authRecovery=false;
db.auth.onAuthStateChange(event=>{if(event==="PASSWORD_RECOVERY"){window.authRecovery=true;window.dispatchEvent(new Event("ananda-password-recovery"))}});
